# Nysql数据库配置信息
mysql:
  path: "127.0.0.1"
  port: "3306"
  config: "charset=utf8&parseTime=True&loc=Local"
  db-name: "gorm"
  username: "gorm"
  password: "000000"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[free]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
